apiVersion: v2
appVersion: 1
name: outline
version: 0.0.8
description: outline wiki
dependencies:
- name: replicated-library
  #repository: file://../../../helm-charts-library/charts/replicated-library
  repository: https://replicatedhq.github.io/helm-charts
  version: '^0.13.7'
- name: postgresql
  repository: https://charts.bitnami.com/bitnami
  #repository: oci://registry-1.docker.io/bitnamicharts
  version: 12.6.5
  condition: postgresql.enabled
- name: redis
  repository: https://charts.bitnami.com/bitnami
  #repository: oci://registry-1.docker.io/bitnamicharts
  version: 17.11.8
  condition: redis.enabled
- name: minio
  repository: https://charts.bitnami.com/bitnami
  #repository: oci://registry-1.docker.io/bitnamicharts
  version: 12.6.9
  condition: minio.enabled
kubeVersion: '>=1.20.0-0'
