apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "samba.fullname" . }}
  labels:
    app: {{ template "samba.name" . }}
    chart: {{ template "samba.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: {{ template "samba.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      annotations:
      labels:
        app: {{ template "samba.name" . }}
        release: {{ .Release.Name }}
    spec:
      {{- if .Values.antiaff.enabled }}
      affinity:
        podAntiAffinity:
        {{- if .Values.antiaff.strict }}
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
        {{- else }}
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:  
              labelSelector:
        {{- end }}
                matchExpressions:
                - key: release
                  operator: In
                  values:
                  - {{ .Release.Name }}
              topologyKey: "kubernetes.io/hostname"
      {{- end }}
      {{- if .Values.nmbd }}
      hostNetwork: true
      {{- else }}
      hostNetwork: {{ .Values.hostNetwork }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          env:
          {{- if .Values.charmaps }}
          - name: CHARMAP
            value: {{ $first := true -}}{{- range $key, $value := .Values.charmaps -}}
                {{- if $first -}}
                    {{- $first = false -}}
                {{- else -}}
                    ,
                {{- end }}
                {{- $key -}}:{{- $value -}}
            {{- end }}
          {{- end }}
          {{- if .Values.generic }}
            {{- range $idx, $map := .Values.generic }}
          - name: GENERIC{{ $idx }}
            value: {{ $map.section }};{{ $map.parameter }}
            {{- end }}
          {{- end }}
          {{- if .Values.global }}
            {{- range $idx, $value := .Values.global }}
          - name: GLOBAL{{ $idx }}
            value: {{ $value }}
            {{- end }}
          {{- end }}
          {{- if .Values.nmbd }}
          - name: NMBD
            value: ENABLED
          {{- end }}
          {{- if .Values.permissions }}
          - name: PERMISSIONS
            value: SET
          {{- end }}
          {{- if .Values.disableRecycle }}
          - name: RECYCLE
            value: DISABLED
          {{- end }}
          {{- if .Values.shares }}
            {{- range $idx, $map := .Values.shares }}
          - name: SHARE{{ $idx }}
            value: {{ $map.name }};{{ $map.path }}
                {{- if $map.browse -}};yes{{- else }};no{{- end }}
                {{- if $map.readonly -}};yes{{- else }};no{{- end }}
                {{- if $map.guest -}};yes{{- else }};no{{- end }}
                {{- if not $map.users -}}
                    ;all
                {{- else -}}
                    ;
                    {{- $first := true -}}
                    {{- range $user := $map.users -}}
                        {{- if $first -}}
                            {{- $first = false -}}
                        {{- else -}}
                            ,
                        {{- end -}}
                        {{- $user }}
                    {{- end }}
                {{- end }}
                {{- if not $map.admins -}}
                    ;none
                {{- else -}}
                    ;
                    {{- $first := true -}}
                    {{- range $admin := $map.admins -}}
                        {{- if $first -}}
                            {{- $first = false -}}
                        {{- else -}}
                            ,
                        {{- end -}}
                        {{- $admin }}
                    {{- end }}
                {{- end }}
                {{- if not $map.writelist -}}
                    ;none
                {{- else -}}
                    ;
                    {{- $first := true -}}
                    {{- range $wluser := $map.writelist -}}
                        {{- if $first -}}
                            {{- $first = false -}}
                        {{- else -}}
                            ,
                        {{- end -}}
                        {{- $wluser }}
                    {{- end }}
                {{- end }}
                {{- if not $map.comment -}}
                    ;none
                {{- else -}}
                    ;{{- $map.comment -}}
                {{- end -}}
            {{- end }}
          {{- end }}
          {{- if .Values.smb }}
          - name: SMB
            value: DISABLED
          {{- end }}
          {{- if .Values.TZ }}
          - name: TZ
            value: {{ .Values.TZ | quote }}
          {{- end }}
          {{- if .Values.wideLinks }}
          - name: WIDELINKS
            value: ENABLED
          {{- end }}
          {{- if .Values.workgroup }}
          - name: WORKGROUP
            value: {{ .Values.workgroup | quote }}
          {{- end }}
          {{- if .Values.UID }}
          - name: USERID
            value: {{ .Values.UID | quote }}
          {{- end }}
          {{- if .Values.GID }}
          - name: GROUPID
            value: {{ .Values.GID | quote }}
          {{- end }}
          {{- if .Values.include }}
          - name: INCLUDE
            value: {{ .Values.include | quote }}
          {{- end }}
          {{- if .Values.usersSecret }}
          envFrom:
            - secretRef:
                name: {{ .Values.usersSecret }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          readinessProbe:
            tcpSocket:
              port: 445
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 445
            initialDelaySeconds: 10
            periodSeconds: 30
          ports:
            - containerPort: 445
              name: samba-445
              protocol: TCP
            #- containerPort: 139
            #  name: samba-139
            #  protocol: TCP
            {{- if .Values.nmbd }}
            - containerPort: 137
              name: nmbd-137
              protocol: UDP
            - containerPort: 138
              name: nmbd-138
              protocol: UDP
            {{- end }}
          {{- if .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml .Values.volumeMounts | nindent 12 }}
          {{- end }}
      {{- if .Values.volumes }}
      volumes:
        {{- toYaml .Values.volumes | nindent 9 }}
      {{- end }}
