{{- if .Values.nmbd }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "samba.fullname" . }}-udp
  labels:
    app: {{ template "samba.name" . }}
    chart: {{ template "samba.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.serviceUDP.annotations }}
  annotations:
{{ toYaml .Values.serviceUDP.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.serviceUDP.type }}
  {{- if .Values.serviceUDP.loadBalancerIP }}
  loadBalancerIP: {{ .Values.serviceUDP.loadBalancerIP }}
  {{- end }}
  {{- if or (eq .Values.serviceUDP.type "NodePort") (eq .Values.serviceUDP.type "LoadBalancer") }}
  externalTrafficPolicy: {{ .Values.serviceUDP.externalTrafficPolicy }}
  {{- end }}
  ports:
    - port: 137
      targetPort: nmbd-137
      protocol: UDP
      name: nmbd-137
    - port: 138
      targetPort: nmbd-138
      protocol: UDP
      name: nmbd-138
  selector:
    app: {{ template "samba.name" . }}
    release: {{ .Release.Name }}
{{- end }}
