apiVersion: v1
kind: Service
metadata:
  name: {{ template "samba.fullname" . }}-tcp
  labels:
    app: {{ template "samba.name" . }}
    chart: {{ template "samba.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.serviceTCP.annotations }}
  annotations:
{{ toYaml .Values.serviceTCP.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.serviceTCP.type }}
  {{- if .Values.serviceTCP.loadBalancerIP }}
  loadBalancerIP: {{ .Values.serviceTCP.loadBalancerIP }}
  {{- end }}
  {{- if or (eq .Values.serviceTCP.type "NodePort") (eq .Values.serviceTCP.type "LoadBalancer") }}
  externalTrafficPolicy: {{ .Values.serviceTCP.externalTrafficPolicy }}
  {{- end }}
  ports:
    - port: 445
      targetPort: samba-445
      protocol: TCP
      name: samba-445
    #- port: 139
    #  targetPort: samba-139
    #  protocol: TCP
    #  name: samba-139
  selector:
    app: {{ template "samba.name" . }}
    release: {{ .Release.Name }}
