apiVersion: v1
kind: Service
metadata:
  name: {{ template "sftp.fullname" . }}
  labels:
    app: {{ template "sftp.name" . }}
    chart: {{ template "sftp.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- if or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer") }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  {{- end }}
  ports:
    - port: {{ .Values.sshPort }}
      targetPort: sftp-ssh
      protocol: TCP
      name: sftp-ssh
  selector:
    app: {{ template "sftp.name" . }}
    release: {{ .Release.Name }}
