 name: Release Charts
 on:
   push:
     branches:
       - master
 jobs:
   release:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
         uses: actions/checkout@v2
         with:
             submodules: recursive
             fetch-depth: 0

       - name: Configure Git
         run: |
           git config user.name "$GITHUB_ACTOR"
           git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

       - name: Install Helm
         uses: azure/setup-helm@v1
         with:
           version: v3.6.3

       - name: Generate KOTS files
         env:
           CHART_VERSION: 1.76.1
         run: |
           export KOTS_VERSION=${CHART_VERSION%-*}
           export KOTS_TAG=v${KOTS_VERSION}
           curl -O -L https://raw.githubusercontent.com/replicatedhq/kots/${KOTS_TAG}/.image.env
           export $(cat .image.env | sed 's/#.*//g' | xargs)
           cd charts/kots-helm
           envsubst < Chart.yaml.tmpl > Chart.yaml
           envsubst < values.yaml.tmpl > values.yaml

       - name: Run chart-releaser for charts
         uses: helm/chart-releaser-action@v1.2.1
         env:
           CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
